DC ESS BUS Functions
JonathanOrr/A321Neo-FXPL pull request #50
Opened 2021-07-31 06:28 UTC by frazer380

Upon loss of DC ESS BUS power, ECAM actions (except ALL, RCL, CLR, EMER CMD, and STS) are inop, and the GPWS fails.

2021-07-31 06:55 UTC, JonathanOrr commented
![image](https://user-images.githubusercontent.com/61325694/127731603-7ae782fa-ed9c-4cb1-ad81-745a102298e9.png)
The power source of GPWS system is AC 1.

2021-07-31 07:02 UTC, frazer380 commented
Yes I've realized this. However ECAM code should still work.
https://youtu.be/dyJeE4pgmRo?t=192

2021-07-31 07:05 UTC, hkkhkhkhk commented
Can you try not to reference from a video from 2008....
We have the neo manuals and we follow them 🥲

2021-07-31 07:06 UTC, hkkhkhkhk commented
Anyways we'll take a look

2021-07-31 07:08 UTC, JonathanOrr commented
You will need to provide document-based evidence for us to review. However, we will take a look. Also, outside the failure manager, FAILURE datarefs are not to be written to.

2021-07-31 19:55 UTC, rico23rico requested changes
Ok, so... @frazer380 you're right that the pushbuttons should not work without DC ESS. But you need to make the following edits before merge:
- I suggest to put an opposite `if` at the beginning of the function like:
```lua
function ecam_user_press_page_button(phase, which_page)
    if get(DC_ess_bus_pwrd) == 0 then
        return
    end 
    ...
```
otherwise, you are changing the other variables like `Ecam_current_status` or `press_start_time` which would make the state inconsistent.
- Check that the button is not STS (if it is STS, it should work in any case)
- Remove the GPWS code, which is already correct [here](https://github.com/JonathanOrr/A321Neo-FXPL/blob/b6f2067b79df1a3f1d7280d465e4672779e124b4/plugins/sasl/data/modules/Custom%20Module/GPWS.lua#L83).

2021-08-03 00:02 UTC, frazer380 commented
Okay, I've fixed it.

2021-08-11 19:02 UTC, rico23rico commented
@frazer380 I lost the notification of this PR. I'll test it next week and I'll let you know :)

2023-05-31 03:24 UTC, closed without merging